### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by parkerault** [iyuuya/trello.vim#13]
https://github.com/iyuuya/trello.vim/blob/db00fc03278c9d7b8f3bdd9d65295aa2af4ffe79/plugin/trello.vim#L11

Is this a private API key?

**Comment by iyuuya** [comment]
It is Developer API Key.
This key is used for authentication to obtain a token.
You can use the Trello API with a pair of key and token.
If you want to use your own key please override the variable.
Probably if you are logged in trello you will get the key.
https://trello.com/app-key

Sorry to keep in mind that I have often forgotten, so please look here.
https://trello.readme.io/docs/api-introduction

I'm not good at writing English, and I may make many mistakes. So, please be patient with me.

**Comment by parkerault** [comment]
I was actually just making sure you didn't accidentally commit a secret key to a public repo. Sorry I didn't make that clear.

**Comment by iyuuya** [comment]
I was slightly worried and fixed it. thanks!

**Comment by iyuuya** [comment]
https://trello.com/app-key
> API Keys
Please keep your API Secret safe. Because your API Key is public for any client-side applications, we do not currently offer a way to reset it.

これが分かりづらいんですが、
> API Key

これは`Developer API Keys > Key: xxxxxx`のこと。

> API Secret

これは`Developer API Keys > OAuth > Secret: xxxxxxxx`のこと。
また`API Key is public`なので問題ないと理解していて、`Please keep your API Secret safe.`なので`Secret:`は公開してはいけないって事ですよね。

どちらにしてもユーザーはTokenを取得しないと情報は抜かれませんが、公開していたKeyで悪さされたときの責任の所在はKeyの所有者になりそうですね。
なのでやはり公開しない方が身の為かもしれません。

公開して相当時間が経ってるので、TrelloにはKey/Secretのリセットを早く実装してほしいところ。

**Comment by iyuuya** [comment]
![image](https://user-images.githubusercontent.com/147351/36218230-0e3fe2c8-11f7-11e8-9739-d408a497b4cb.png)

> 利用者が全てのリスクと責任を負うものとします。

問題なさそう!

**Comment by iyuuya** [comment]
English↓

> **Foo App** is not affiliated with Trello in any way, and by permitting access to your content you assume all related risks and liabilities.
